apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: lybu4u8by-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-36126ca9e4.phvd.p3.openshiftapps.com/rhtap/rhtap-qe:df3c26dc405b842afe2492a1e4866782e50902f9@sha256:04a7e4b29d747ce75570c899184963f5315a5e0407fdb5de966760b59e6caacf
        name: container-image  
